### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Fawadkhanfk** [Sicks3c/Reconizer#1]
![sss](https://user-images.githubusercontent.com/25926307/110361870-81415b00-8038-11eb-9a67-8b3ce6189c8f.PNG)

showing this error

**Comment by Sicks3c** [comment]
Hello @Fawadkhanfk 

Thank you for reaching out regarding your issue
This issue is caused because of the memory usage. and unrelated to the tool
You can minimize the dns queries of amass as a workaround

Cheers
